build:
  version: "1.0"

cards:
  message: "Welcome to hdfc cards related prod APIs "
  contactDetails:
    name: "Priti  - Product Owner"
    email: "priti@hdfc.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721
