server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/sahilkaul52/spring-cloud-config-v2.git"
          default-label: main
          timeout: 5
          force-pull: true
          clone-on-start: true